### ISSUE TITLE
پرداخت الکترونیک سپهر

### ISSUE THREAD

**Issue by persianopencart** [Matin-B/SNI-Bypass#2]
سلام
خسته نباشید و ممنون بابت اسکریپت
برای پورت 8080 پرداخت الکترونیک سپهر کانفیگ چطوری میشه؟

**Comment by Matin-B** [comment]
درود
وقت بخیر

با اسکریپت کنونی شما هیچ پورت خاصی را تنظیم نمیکنید و در واقع کل ترافیک دامنه های مورد نظر از سرور sni proxy گذر میکنند.
بر اساس آموزش زیر بدون مشکل میتونید از اسکریپت برای تمام درگاه ها استفاده کنید:
https://webdade.com/blog/iran-access-and-non-connection-of-payment-gateway
